version: '3.8'

services:
  # 1. BASE DE DATOS CENTRAL
  mysql_server:
    image: mysql:8.0
    container_name: mysql_db_smartlogix
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - smartlogix_net

  # 2. SERVIDOR DE MENSAJERÍA RABBITMQ
  rabbitmq_server:
    image: rabbitmq:3-management
    container_name: rabbitmq_smartlogix
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - smartlogix_net

  # 3. MICROSERVICIO DE CATÁLOGO
  ms-catalogo:
    build: ./MS_CATALOGO
    container_name: ms_catalogo_app
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=mysql_server
    depends_on:
      - mysql_server
    networks:
      - smartlogix_net

  # 4. MICROSERVICIO DE PAGOS
  ms-pagos:
    build: ./MS_PAGOS
    container_name: ms_pagos_app
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - SLACK_WEBHOOK_URL=TU_URL_DE_SLACK_AQUI
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 5. MICROSERVICIO DE MENSAJERÍA
  ms-mensajeria:
    build: ./MS_MENSAJERIA
    container_name: ms_mensajeria_app
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - MAIL_USER=mensajeria.smartlogix@gmail.com
      - MAIL_PASS=TU_PASSWORD_AQUI
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 6. BACKEND FOR FRONTEND (BFF)
  ms-bff:
    build: ./BFF_WEB
    container_name: bff_web_app
    ports:
      - "8080:8080"
    environment:
      - URL_MS_CATALOGO=http://ms-catalogo:8088/api/productos
      - URL_MS_PAGOS=http://ms-pagos:8082/api/pagos
      - URL_MS_MENSAJERIA=http://ms-mensajeria:8084/api/mensajeria
    depends_on:
      - ms-catalogo
      - ms-pagos
      - ms-mensajeria
    networks:
      - smartlogix_net

networks:
  smartlogix_net:
    driver: bridge
    