version: '3.8'

services:
  # 1. BASE DE DATOS CENTRAL (Una instancia para los 3 microservicios)
  mysql_server:
    image: mysql:8.0
    container_name: mysql_db_smartlogix
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permite entrar sin clave, como en tu XAMPP
    ports:
      - "3306:3306"
    networks:
      - smartlogix_net

  # 2. SERVIDOR DE MENSAJERÍA RABBITMQ
  rabbitmq_server:
    image: rabbitmq:3-management
    container_name: rabbitmq_smartlogix
    ports:
      - "5672:5672"   # Puerto de comunicación interna
      - "15672:15672" # Puerto de la interfaz web para ver las colas
    networks:
      - smartlogix_net

  # 3. MICROSERVICIO DE CATÁLOGO
  ms-catalogo:
    build: ./MS_CATALOGO
    container_name: ms_catalogo_app
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=mysql_server
    depends_on:
      - mysql_server
    networks:
      - smartlogix_net

  # 4. MICROSERVICIO DE PAGOS
  ms-pagos:
    build: ./MS_PAGOS
    container_name: ms_pagos_app
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - SLACK_URL=http://localhost_falso # Aquí podrías poner tu URL real si quieres
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 5. MICROSERVICIO DE MENSAJERÍA
  ms-mensajeria:
    build: ./MS_MENSAJERIA
    container_name: ms_mensajeria_app
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - MAIL_USER=mensajeria.smartlogix@gmail.com
      - MAIL_PASS=zvps zmyl yyjk exwo # Tus 16 letras
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 6. BACKEND FOR FRONTEND (BFF)
  ms-bff:
    build: ./BFF_WEB
    container_name: bff_web_app
    ports:
      - "8080:8080"
    environment:
      - URL_MS_CATALOGO=http://ms-catalogo:8088/api/productos # Ruta interna al contenedor
    depends_on:
      - ms-catalogo
    networks:
      - smartlogix_net

# Definimos la red privada
networks:
  smartlogix_net:
    driver: bridge
