version: '3.8'

services:
  # 1. BASE DE DATOS CENTRAL
  mysql_server:
    image: mysql:8.0
    container_name: mysql_db_smartlogix
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - smartlogix_net

  # 2. SERVIDOR DE MENSAJERÍA RABBITMQ
  rabbitmq_server:
    image: rabbitmq:3-management
    container_name: rabbitmq_smartlogix
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - smartlogix_net

  # 3. MICROSERVICIO DE CATÁLOGO
  ms-catalogo:
    build: ./MS_CATALOGO
    container_name: ms_catalogo_app
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=mysql_server
    depends_on:
      - mysql_server
    networks:
      - smartlogix_net

  # 4. MICROSERVICIO DE PAGOS
  ms-pagos:
    build: ./MS_PAGOS
    container_name: ms_pagos_app
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - SLACK_WEBHOOK_URL=TU_URL_DE_SLACK_AQUI
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 5. MICROSERVICIO DE MENSAJERÍA
  ms-mensajeria:
    build: ./MS_MENSAJERIA
    container_name: ms_mensajeria_app
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - MAIL_USER=mensajeria.smartlogix@gmail.com
      - MAIL_PASS=TU_PASSWORD_AQUI
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 6. MICROSERVICIO DE ENVÍOS
  ms-envios:
    build: ./ms_envios
    container_name: ms_envios_app
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 7. IDENTITY PROVIDER (IDP)
  ms-idp:
    build: ./ms_idp
    container_name: ms_idp_app
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_server:3306/smartlogix_idp?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_RABBITMQ_HOST=rabbitmq_server
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 8. MICROSERVICIO DE USUARIOS
  ms-usuario:
    build: ./ms_usuario
    container_name: ms_usuario_app
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=mysql_server
      - RABBITMQ_HOST=rabbitmq_server
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_server:3306/smartlogix_usuarios?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_RABBITMQ_HOST=rabbitmq_server
    depends_on:
      - mysql_server
      - rabbitmq_server
    networks:
      - smartlogix_net

  # 9. BACKEND FOR FRONTEND (BFF)
  ms-bff:
    build: ./BFF_WEB
    container_name: bff_web_app
    ports:
      - "8080:8080"
    environment:
      - URL_MS_CATALOGO=http://ms-catalogo:8088/api/productos
      - URL_MS_PAGOS=http://ms-pagos:8082
      - URL_MS_MENSAJERIA=http://ms-mensajeria:8083/api/mensajeria
      - URL_MS_IDP=http://ms-idp:8084/api/v1/auth
      - URL_MS_USUARIO=http://ms-usuario:8085/api/usuarios
    depends_on:
      - ms-catalogo
      - ms-pagos
      - ms-mensajeria
      - ms-idp
      - ms-usuario
    networks:
      - smartlogix_net

  # 10. GESTOR DE BASE DE DATOS
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_smartlogix
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql_server
      PMA_USER: root
      PMA_NO_PASSWORD: "true"
    depends_on:
      - mysql_server
    networks:
      - smartlogix_net

  # 11. FRONTEND

networks:
  smartlogix_net:
    driver: bridge

