# Puerto de entrada para el Frontend y Postman
server.port=8080

# Nombre del microservicio
spring.application.name=ms_bff

# Configuración para ver los mensajes de error claritos en Postman
spring.web.error.include-message=always

# ==========================================
# RUTAS DE MICROSERVICIOS (Preparado para Docker)
# ==========================================
# Si existe la variable de entorno URL_MS_CATALOGO, la usa. Si no, usa localhost (para pruebas locales).
# Rutas para Catálogo, Pagos y Mensajería
url.ms.catalogo=${URL_MS_CATALOGO:http://localhost:8088/api/productos}
url.ms.pagos=${URL_MS_PAGOS:http://localhost:8082/api/pagos}
url.ms.mensajeria=${URL_MS_MENSAJERIA:http://localhost:8084/api/mensajeria}


