server {
    listen 80;

    # 1. Rutas de la API: Todo lo que empiece por /api se va al BFF
    location /api/ {
        # Reescribe /api/... a /api/v1/... antes de reenviar, igual que hacía el proxy de Vite en desarrollo
        rewrite ^/api/(.*)$ /api/v1/$1 break;

        proxy_pass http://ms-bff:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Frontend: Cualquier otra cosa se sirve como archivo estático
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

